const trainings = [
  {
    '_id': '1',
    'name': 'Free Consultation',
    'image': '/images/ClassPic_4.jpeg', 
    'description':' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum.',
    'category': 'Beginner',
    'bookingInfo': ' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum.',
    'openSlots': 15,
    'Hours': 1,
    'rating': 4.0,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'JoinMyTeam',
    'image': '/images/ClassPic_5.PNG', 
    'description': ' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum.',
    'category': 'Intermediate',
    'bookingInfo': ' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum.',
    'openSlots': 15,
    'Hours': 1,
    'rating': 4.5,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Learn More',
    'image': '/images/ClassPic_2.JPG',
    'description': ' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum.',
    'category': 'Advance',
    'brand': 'Alcantara',
    'category': 'ADVANCE',
     'bookingInfo': ' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum.',
    'openSlots': 0,
    'Hours': 1.5,
    'rating': 5,
    'numReviews': 12,
  },
]

export default trainings