const trainings = [
  {
    '_id': '1',
    'name': 'Fundamentals And Basics',
    'image': '/images/ClassPic_4.jpeg', 
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum.',
    'category': 'Beginner',
    'price': 40.00,
    'openSlots': 15,
    'Hours': 1,
    'rating': 4.0,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'JoinMyTeam',
    'image': '/images/ClassPic_5.PNG',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum.',
    'category': 'Intermediate',
    'price': 50.00,
    'openSlots': 15,
    'Hours': 1,
    'rating': 4.5,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'HEROS',
    'image': '/images/ClassPic_2.JPG',
    'description':'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum.',
    'category': 'Advance',
    'brand': 'Alcantara',
    'category': 'ADVANCE',
    'price': 60.00,
    'openSlots': 0,
    'Hours': 1.5,
    'rating': 5,
    'numReviews': 12,
  },
]

export default trainings